### ISSUE TITLE
Kubernetes Dashboard error - x509 cert signed by unknown authority

### ISSUE THREAD

**Issue by deinspanjer** [TheNewNormal/kube-cluster-osx#47] opened 2016-06-12 22:18 UTC
Working with a clean install of kube-cluster 2.8.
After starting the cluster, I can run FleetUI, but when I try to run Kubernetes Dashboard, I see the following 500 error:

Internal Server Error (500)
Get https://10.100.0.1:443/api/v1/replicationcontrollers: x509: certificate signed by unknown authority

**Comment by deinspanjer** [comment] 2016-06-12 22:23
I tried using the kube-cluster option "Restore/Update fleet unites", and it destroyed and restarted them, but after it reported everything was done, the dashboard still gives me an error although now it is a slightly different one:

Internal Server Error (500)
the server has asked for the client to provide credentials (get replicationControllers)

**Comment by deinspanjer** [comment] 2016-06-12 22:38
Ugh. I figured out the source of my problem if not the reason.  I already had an id_rsa key in my .ssh directory which was a symlink to my normally used key also in .ssh but with a different name.

The setup/install script found that key and used it, but apparently there was something that k8s didn't like about it (probably that it was a symlink?).  When I realized it was a symlink, I tried deleting and creating a new fresh key and now the dashboard is working properly.

**Comment by rimusz** [comment] 2016-06-13 07:46
awesome, so we can close the issue then

**Closed as completed by rimusz** 2016-06-13 07:46 UTC

**Comment by deinspanjer** [comment] 2016-06-13 11:47
We can, I didn't do so cause I wanted to make sure you saw what the symptom and behavior was in case there was anything in kube-cluster that should be improved.

**Comment by gajus** [comment] 2016-06-26 16:44
I am getting this on a fresh install of Kube-Solo for OS X v0.6.6.

In addition to this, when I start the VM and SSH to k8solo-01 and try `kubectl get po`, I get an error:

```
core@k8solo-01 ~ $ kubectl get po
Unable to connect to the server: dial tcp: lookup localhost on 192.168.64.1:53: server misbehaving
```

VM appears to start without issues:

```
Starting VM ...
> booting k8solo-01
[corectl] stable/1010.5.0 already available on your system
[corectl] '/Users/gajus' was already available to VMs via NFS
[corectl] started 'k8solo-01' in background with IP 192.168.64.3 and PID 886

Waiting for VM to be ready...
\
fleetctl list-machines:
MACHINE     IP      METADATA
f487abb5... 192.168.64.3    -

Waiting for Kubernetes cluster to be ready. This can take a few minutes...
\
kubernetes nodes list:
NAME           STATUS    AGE
192.168.64.3   Ready     6m
```

> I already had an id_rsa key in my .ssh directory which was a symlink to my normally used key also in .ssh but with a different name.

I do have an existing `id_rsa`, but it is not symlinked.

**Comment by rimusz** [comment] 2016-06-26 16:47
@gajus Are you using preset `OS Shell` via menu? as that points to the right IP, in your case it should be the  192.162.64.3

kubectl is not set inside the VM.

**Comment by gajus** [comment] 2016-06-26 16:57
> @gajus Are you using preset OS Shell via menu? as that points to the right IP, in your case it should be the 192.162.64.3

I am. The URL that the "Kubernetes Dashboard" opens (via the menu) is:

http://192.168.64.3:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/replicationcontrollers

The error that it shows is:

> Internal Server Error (500)
> Get https://10.100.0.1:443/api/v1/replicationcontrollers: x509: certificate signed by unknown authority

**Comment by rimusz** [comment] 2016-06-26 16:59
I cannot reproduce that cert problem myself, so do not know why kube dashboard is not working
