### ISSUE TITLE
UPing on fresh install fails

### ISSUE THREAD

**Issue by wichert** [TheNewNormal/kube-cluster-osx#19] opened 2016-02-08 10:36 UTC
I did the following:
1. Download the v0.1.9 release DMG
2. Unpack the DMG
3. Run Kube-Cluster
4. Select _Up_ from the menu

At that point creation of the initial nodes was started, but failed:

```
Data disks do not exist, they will be created now ...

Creating 1GB Data disk for Master ...
   1GiB 0:00:03 [ 310MiB/s] [================================>] 100%
Created 1GB Data disk for Master

Please type Nodes Data disk size in GBs followed by [ENTER]:
[default is 10]:

Creating 10GB Data disk for Node1...
  10GiB 0:00:36 [ 283MiB/s] [================================>] 100%
Created 10GB Data disk for Node1

Creating 10GB Data disk for Node2...
  10GiB 0:00:32 [ 317MiB/s] [================================>] 100%
Created 10GB Data disk for Node2

Starting k8smaster-01 VM ...
> booting k8smaster-01
Error: open alpha: no such file or directory

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


Master VM has not booted, please check '~/kube-cluster/logs/master_vm_up.log' and report the problem !!!
```

The `master_vm_up.log` file contains the following:

```
> booting k8smaster-01
Error: open alpha: no such file or directory

Usage: 
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"
```

**Comment by rimusz** [comment] 2016-02-08 10:46
did you run `kube-cluster` app directly from the dmg?

**Comment by wichert** [comment] 2016-02-08 10:46
I copied it out to another folder first.

**Comment by rimusz** [comment] 2016-02-08 10:48
that strange then.
have you followed all steps in the shell script?

**Comment by rimusz** [comment] 2016-02-08 10:51
I do not see that alpha iso image was downloaded there

**Comment by wichert** [comment] 2016-02-08 10:57
I think what happened here is that I was confused by the documention. Your README says:

> Start the `Kube-Cluster` and and `Initial setup of Kube-Cluster VMs` will run

That made me assume the initial setup is run automatically. Since all menu options said no nodes were running I tried the `Up` option, which resulted in that error. What I probably should have done is run the `Initial setup of Kube-Cluster VMs` from the `Setup` sub-menu manually.

**Comment by rimusz** [comment] 2016-02-08 11:00
it does run automatically if App detects that if there is no `~/kube-cluster-osx` folder, but also `Up` starts the install process if there is no `~/kube-cluster-osx` folder

**Comment by mrardon** [comment] 2016-02-16 00:28
I am also experiencing a similar problem but not sure if it is related. Fresh install went through the setup prompts and when it came to trying to boot the VMs I get the following:

```
> booting k8smaster-01
[corectl] alpha/955.0.0 already available on your system
[corectl] '/Users/mrardon' was already available to VMs via NFS
Error: Unable to grab VM's IP after 30s (!)... Aborting

Usage: 
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"
```

**Comment by rimusz** [comment] 2016-02-16 08:51
@mrardon latest alpha/955 does not work properly yet, please use beta/stable

**Comment by mrardon** [comment] 2016-02-16 15:25
Thanks, beta seems to work for now - I did not set it to alpha, so not sure how it got that way. Thanks.

**Comment by rimusz** [comment] 2016-02-16 15:54
@mrardon which exactly channel option did you chose at the install part?

**Comment by mrardon** [comment] 2016-02-16 16:10
Ahh don't remember what I picked must have chosen it there.

**Comment by rimusz** [comment] 2016-02-16 16:12
hmm, just trying to find the issue there

**Comment by mrardon** [comment] 2016-02-16 16:21
Ok I think I found the steps that can reproduce the issue - at least at my end. 

1) Fresh install (I renamed ~/kube-cluster to ~/kube-cluster-old)
2) Input Sudo password, select alpha channel and accepting all other defaults
3) This will fail like I experienced before, however even if you switch channels it will continue to fail with a similar error message to above. 

Resolution:
1) Fresh install again (rename ~/kube-cluster)
2) Input sudo password, select non alpha (I chose beta) and accept other defaults
3) Rest seems to work

This was really confusing as it appeared to be stuck in a loop while `Waiting for Kubernetes cluster to be ready. This can take a few minutes...`. I would suggest making it a little more clear that alpha is not working right now and that should solve the problem. 

It possibly could be caused by me giving up at somepoint and ^C'ing out of it but this was after 40 minutes at least. Anyway it seems to be happy now.

**Comment by rimusz** [comment] 2016-02-16 16:24
alpha 955 is not working properly for sure, but this is alpha it is expected to happen time by time.
I will put a note for the channel choice about it

**Comment by mrardon** [comment] 2016-02-16 16:27
Yeh I agree, I think the issue is that even after changing from the alpha it didn't work, so I guess it wasn't clear that the alpha was still causing the issue. Probably just got half initialized and had to be completely cleared out.

**Comment by rimusz** [comment] 2016-02-16 16:29
yes, if it got half initialised then of course changing channel will not help.
I need to think for more checks for such half initialised setups

**Comment by rimusz** [comment] 2016-02-18 19:33
this issue is related to https://github.com/TheNewNormal/corectl/issues/61 so I'm closing this one

**Closed as completed by rimusz** 2016-02-18 19:33 UTC
